[build-system]
requires = [
    "setuptools>=80",
    "wheel"
]
build-backend = "setuptools.build_meta"

[project]
name = "crazyeights"
version = "0.1.0"
description = "A simple card game"
readme = "README.md"
requires-python = ">=3.12"
dependencies = ["click>=8.0"]
